[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "stock-scraper"
version = "0.1.0"
authors = [
    {name = "Your Name"}
]
description = "A stock data scraper"

[tool.pytest.ini_options]
pythonpath = [
  ".", "src"
]